sudo: enabled
dist: xenial
language: cpp
os: linux

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-5


before_install:
  # Fix for Ubuntu Xenial apt-daily.service triggering
  # https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
  - |
    sudo systemctl stop apt-daily.service &&
    sudo systemctl kill --kill-who=all apt-daily.service &&
    while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
      sleep 1
    done
  - sudo apt update -qq

install: sudo ./gaia/install-dependencies.sh

script:
  - ./gaia/blaze.sh -ninja && cd build-dbg
  - ninja -j4 one

after_failure:
  - pwd
  - find ../third_party/src/ -regex ".*\(err\|out\).log" | xargs -n 3 -t cat
